ignore:
  - "tests/*"
  - "*.md"
  - "*.yml"
  - "*.yaml"
  - "*.json"
  - "*.toml"
  - "*.log"
  - "*.txt"
  - "*.html"
  - "**/setup.py"
  - "dgamore/DGAmore.py"
  - "dgamore/plotting.py"
  - "dgamore/config_parser.py"
  - "dgamore/symmetrize_new.py"
  - "dgamore/mpi_distributor.py"
  - "dgamore/mpi_utils.py"
  - "dgamore/ana_cont.py"
  - "dgamore/max_ent.py"
  - "dgamore/dmft_interface.py"

coverage:
  status:
    project:
      default:
        patch: 85%
        threshold: 0%
        informational: true
comment:
  layout: "reach, diff, flags, files"
  behavior: default